services:
  postgres:
    image: postgres:16 #
    container_name: shared-postgres
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=odoo
    ports:
      - "5432:5432"  
    volumes:
      - shared-postgres-data:/var/lib/postgresql/data
    networks:
      - shared-postgres-network

volumes:
  shared-postgres-data:

networks:
  shared-postgres-network:
    driver: bridge
